app:
  name: DMX Art-Net Checker - Studio
window:
  width: 1024
  height: 768
artnet:
  default_ip: 127.0.0.1
  default_port: 6454
  default_universe: 0
dmx:
  display_channels:
    start: 129
    end: 144
logging:
  level: info
  file_logging: false
  log_file: dmx-studio.log
  max_file_size: 10MB
  max_files: 3
