# DMX Art-Net Checker Configuration

# Application Settings
app:
  name: "DMX Art-Net Checker"
  
# Window Settings
window:
  width: 1200
  height: 800

# Art-Net Connection Settings
artnet:
  # Default connection configuration
  default_ip: "192.168.1.255"
  default_port: 6454
  default_universe: 0

# DMX Channel Settings
dmx:
  # Channel display range
  display_channels:
    start: 1
    end: 16

# Logging Settings
logging:
  level: "info"  # debug, info, warn, error
  file_logging: true
  log_file: "dmx-artnet.log"
  max_file_size: "10MB"
  max_files: 5
